apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-kubernetes
spec:
  crossplane:
    version: ">=v1.5"
  dependsOn:
  # - provider: crossplane/provider-aws
  #   version: ">=v0.23.0"
  # - provider: crossplane/provider-gcp
  #   version: ">=v0.19.0"
  # - provider: crossplane/provider-jet-azure
  #   version: ">=v0.5.0"
  # - provider: crossplane/provider-digitalocean
  #   version: ">=v0.1.0"
  - provider: crossplane/provider-helm
    version: ">=v0.9.0"
  - provider: crossplane/provider-kubernetes
    version: ">=v0.3.0"
