apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeclusters.devopstoolkitseries.com
spec:
  connectionSecretKeys:
  - kubeconfig
  defaultCompositionRef:
    name: cluster-google
  group: devopstoolkitseries.com
  names:
    kind: CompositeCluster
    plural: compositeclusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this Cluster that other objects will use to refer to it.
              parameters:
                type: object
                properties:
                  version:
                    description: The Kubernetes version for the cluster.
                    type: string
                  nodeSize:
                    description: The size of the nodes; small, medium, large
                    type: string
                  minNodeCount:
                    description: The minimum number of nodes
                    type: integer
                    default: 1
                required:
                - nodeSize
            required:
            - id
            - parameters
          status:
            type: object
            properties:
              clusterName:
                description: The name of the cluster
                type: string
              controlPlaneStatus:
                description: The status of the control plane
                type: string
              nodePoolStatus:
                description: The status of the node pool
                type: string
    additionalPrinterColumns:
    - name: clusterName
      type: string
      jsonPath: ".status.clusterName"
    - name: controlPlane
      type: string
      jsonPath: ".status.controlPlaneStatus"
    - name: nodePool
      type: string
      jsonPath: ".status.nodePoolStatus"
